Task 2
NazarovAn/DirectumLab-2021-Nazarov_AA pull request #1
Opened 2021-03-03 08:54 UTC by NazarovAn

Выполнил задание по второй лекции.

2021-03-03 12:43 UTC, LikhvarDS requested changes
Некоторые замечания требуют больших изменений

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/Meeting.cs
> +        }
Т.к. нет доп. логики в сеттере/геттере, то можно воспользоваться автосвойствами.
Пример: 
`public string StartDate  { get; set; }`
В таком случае поля startDate, endDate, duration будут не нужны.

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/Meeting.cs
> +            get { return this.duration; }
Вычисление длительности можно написать прямо в геттере. Вычесть из окончания начало.

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/Meeting.cs
> +        public string StartDate
мелочь: наверное лучше убрать из названия свойства Date.

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/Meeting.cs
> +            this.CalculateDuratation();
Это лишнее. 
То есть при создании мы **обязаны** в консоле ввести даты для встречи.
Давай лучше время начала/конца передавать как параметры в конструктор и обозначивать ими свойства.

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/Meeting.cs
> +        }
\+ Лучше их сделать DateTime, а не string.

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/MeetingWithRemind.cs
> +        private Timer ATimer;
Откуда взялось "A"?
Лучше назвать просто timer;

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/MeetingWithRemind.cs
> +                .Substring(0, 16);
С DateTime можно работать и без преобразования его в строку.

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/IRemind.cs
> +        void OnDateCheck(object source, ElapsedEventArgs e);
В задании:

Разработать интерфейс «Напоминание» (IRemind), позволяющий устанавливать и считывать дату-время напоминания о событии.

предполагалось что в интерфейсе будет свойство
DateTime RemindTime { get; set; }

2021-03-03 12:43 UTC, LikhvarDS commented on dotNet module/Task_2/MeetingWithRemind.cs
> +            if (dateNow == startDate.Substring(0, 16))
Заранее напишу, что при сравнении двух DateTime, лучше проверять не точно, а ">=", т.к. мы не можем гарантировать, что текущее время будет совпадать с указанным с точностью до миллисекунды.

2021-03-03 14:04 UTC, NazarovAn commented on dotNet module/Task_2/Meeting.cs
> +        }
Исправил.

2021-03-04 05:25 UTC, LikhvarDS commented
На будущее: проект для 3 задачи можно было добавить в PR для 3 задачи

2021-03-04 05:28 UTC, LikhvarDS commented on dotNet module/Task_2/IRemind.cs
> +        void OnDateCheck(object source, ElapsedEventArgs e);
В задании не говорится об этих методах, но пускай будут

2021-03-04 05:28 UTC, LikhvarDS approved these changes
Принято

2021-03-04 11:59 UTC, merged